import express from 'express'
import swaggerUi from 'swagger-ui-express'
import swaggerJsDoc from 'swagger-jsdoc'

const router = express.Router()

const options = {    
	swaggerDefinition: {
		info: {
			swagger: '2.0',
			// openapi: '3.0.1',
			title: 'Testing API',
			version: '1.0.0',
			description: 'Test Express API with autogenerated swagger doc'
		},
		basePath: '/api/',
		securityDefinitions: {
			jwt: {
				description: 'Standard Authorization header using the Bearer scheme. Example: \"{token}\". No need to add prefix like "bearer"!',
				type: 'apiKey',
				in: 'header',
				name: 'authorization'
			}
		}	
		// for openapi 3.0, doesn't work
		// components: {
		// 	securitySchemes: {
		// 		jwt: {
		// 			description: 'Standard Authorization header using the Bearer scheme. Example: \"bearer {token}\"',
		// 			type: 'apiKey',
		// 			in: 'header',
		// 			name: 'Authorization'
		// 		}
		// 	}
		// }			
	},        
	apis: ['./controllers/*.js']
}

const specs = swaggerJsDoc(options)

router.use(swaggerUi.serve, swaggerUi.setup(specs))

export default router